// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finances;

#nullable disable

namespace finances.Migrations
{
    [DbContext(typeof(FinancialDbContext))]
    partial class FinancialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("finances.FinancialTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FinancialTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.5,
                            Description = "Example Expense",
                            TransactionDate = new DateTime(2024, 4, 30, 15, 56, 47, 229, DateTimeKind.Local).AddTicks(3642),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500.75,
                            Description = "Example Income",
                            TransactionDate = new DateTime(2024, 4, 30, 15, 56, 47, 229, DateTimeKind.Local).AddTicks(3692),
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
